import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const staticFiles = await readdir('.next/static', { recursive: true, withFileTypes: true });
const assets = staticFiles.filter(f => f.isFile() && !f.name.endsWith('.map')).map(f => `${f.parentPath}/${f.name}`.replace('.next/static', '/_next/static'));
const version = createHash('sha256').update(await readFile('.next/BUILD_ID')).digest('hex').slice(0,12);
const precache = ['/', '/manifest.webmanifest', '/icon-192.png', '/icon-512.png', '/apple-touch-icon.png', '/icon-maskable.png', ...assets];
const source = `// Generated by scripts/build-sw.mjs. Build ${version}.
const CACHE = 'sudoku-${version}';
const PRECACHE = ${JSON.stringify(precache)};
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(PRECACHE)));
  // Do not skipWaiting: never replace a running app's assets mid-puzzle.
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(key => key.startsWith('sudoku-') && key !== CACHE).map(key => caches.delete(key)));
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  // One static application: use a consistent shell and its matching build assets.
  if (request.mode === 'navigate' && url.pathname === '/') {
    event.respondWith(caches.open(CACHE).then(cache => cache.match('/')).then(response => response || fetch(request)));
    return;
  }
  // RSC requests are not HTML. Only serve exact precached static resources here.
  if (PRECACHE.includes(url.pathname) && url.pathname !== '/') {
    event.respondWith(caches.open(CACHE).then(cache => cache.match(url.pathname)).then(response => response || fetch(request)));
  }
});
`;
await writeFile('public/sw.js', source);
console.log(`Service worker: ${precache.length} assets, cache sudoku-${version}`);
