// Builds src/lib/lesson-bank.ts: for each lesson, boards where its technique is the easiest next move. The first is the lesson's example.
// Run: node --experimental-strip-types scripts/build-lesson-bank.ts
import { writeFileSync } from 'node:fs';
import { EXPERT_BANK } from '../src/lib/expert-bank.ts';
import { solveWithTechniques } from '../src/lib/difficulty.ts';
import { applyStep, baseCandidates, findStep } from '../src/lib/steps.ts';
import { buildPuzzle } from '../src/lib/sudoku.ts';
import { LESSONS, lessonOf, type LessonId } from '../src/lib/lessons.ts';

const PER_LESSON = 6;
const bank = Object.fromEntries(LESSONS.map(id => [id, [] as string[]])) as Record<LessonId, string[]>;
const full = () => LESSONS.every(id => bank[id].length >= PER_LESSON);

function walk(givens: number[]) {
  const solution = solveWithTechniques(givens).values;
  if (solution.includes(0)) return;
  const values = [...givens]; const candidates = baseCandidates(values);
  const used = new Set<LessonId>();
  for (let step = findStep(values, candidates); step; step = findStep(values, candidates)) {
    const id = lessonOf(step);
    // Pointing and claiming lessons show pairs, so "Find the pointing pair" is always accurate.
    const pairOnly = (id === 'pointing' || id === 'claiming') && step.pattern.length !== 2;
    if (!used.has(id) && !pairOnly && bank[id].length < PER_LESSON) {
      const base = baseCandidates(values);
      const exclusions = base.map((set, i) => [...set].filter(d => !candidates[i].has(d)).join('')).join(',');
      bank[id].push(`{ lesson: '${id}', givens: '${givens.join('')}', values: '${values.join('')}', solution: '${solution.join('')}', exclusions: '${exclusions}' }`);
      used.add(id);
    }
    applyStep(values, candidates, step);
  }
}

for (const entry of EXPERT_BANK) { if (full()) break; walk([...entry].map(Number)); }
for (let seed = 1; seed <= 3000 && !full(); seed++) walk(buildPuzzle({ difficulty: 'hard', seed, clueTarget: 0 }).givens);
for (const id of LESSONS) console.log(`${id}: ${bank[id].length}`);
writeFileSync(new URL('../src/lib/lesson-bank.ts', import.meta.url), `// Generated by scripts/build-lesson-bank.ts. Per lesson, boards where that technique is the easiest next move; the first is the example.
// \`exclusions\` lists, per cell, the candidates already ruled out before this move, comma-separated.
import type { LessonId } from './lessons.ts';

export type LessonBoard = { lesson: LessonId; givens: string; values: string; solution: string; exclusions: string };
export const LESSON_BANK: Record<LessonId, readonly LessonBoard[]> = {
${LESSONS.map(id => `  '${id}': [\n${bank[id].map(b => `    ${b},`).join('\n')}\n  ],`).join('\n')}
};
`);
