// Builds src/lib/expert-bank.ts: puzzles whose hardest required technique is in the expert band.
// Run: node --experimental-strip-types scripts/build-expert-bank.ts [count]
import { writeFileSync } from 'node:fs';
import { countSolutions, peers } from '../src/lib/sudoku.ts';
import { DIFFICULTY_BANDS, ratePuzzle } from '../src/lib/difficulty.ts';

const target = Number(process.argv[2] ?? 300);
function seeded(seed: number) { let s = seed >>> 0; return () => { s += 0x6D2B79F5; let t = s; t = Math.imul(t ^ t >>> 15, t | 1); t ^= t + Math.imul(t ^ t >>> 7, t | 61); return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
function shuffle<T>(items: T[], random: () => number) { const out = [...items]; for (let i = out.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [out[i], out[j]] = [out[j], out[i]]; } return out; }
/** A random full grid, so the bank is not limited to one solution pattern. */
function randomGrid(random: () => number) {
  const grid = Array(81).fill(0);
  const fill = (i: number): boolean => { if (i === 81) return true; for (const d of shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9], random)) { if (peers(i).some(j => grid[j] === d)) continue; grid[i] = d; if (fill(i + 1)) return true; } grid[i] = 0; return false; };
  fill(0); return grid;
}
/** Removes every clue that can go while the solution stays unique. */
function minimal(solution: number[], random: () => number) {
  const givens = [...solution];
  for (const i of shuffle([...Array(81).keys()], random)) { const saved = givens[i]; givens[i] = 0; if (countSolutions(givens) !== 1) givens[i] = saved; }
  return givens;
}
const bank = new Set<string>();
for (let seed = 1; bank.size < target; seed++) {
  const random = seeded(seed * 2654435761);
  const givens = minimal(randomGrid(random), random);
  if (DIFFICULTY_BANDS.expert.includes(ratePuzzle(givens))) bank.add(givens.join(''));
  if (seed % 500 === 0) console.log(`seed ${seed}: ${bank.size}`);
}
writeFileSync(new URL('../src/lib/expert-bank.ts', import.meta.url), `// Generated by scripts/build-expert-bank.ts. Each entry is a puzzle's 81 givens (0 = empty), rated in the expert band.\nexport const EXPERT_BANK: readonly string[] = [\n${[...bank].map(g => `  '${g}',`).join('\n')}\n];\n`);
console.log(`wrote ${bank.size} puzzles`);
